### ISSUE TITLE
[Drain Safe] Use new address input component

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#198] opened 2021-11-18 08:12 UTC
## Overview
Currently on Drain Safe we are using a custom address input. We should use the new address input component from `safe-react-components` that includes EIP-3770 support, validation and ENS name resolution.

![Screenshot 2021-11-02 at 09 52 58](https://user-images.githubusercontent.com/92332710/139819504-af747169-4ebb-4a33-998b-5d0c2a07babe.png)

## Goals
Add new address input component with latest improvements

## Requirements
ENS should work on that chains that support it
 - Mainnet
 - Rinkeby

**Comment by mikheevm** [comment] 2021-11-22 14:48
Atm the issue is blocked by https://github.com/gnosis/safe-react-components/pull/167

**Comment by mikheevm** [comment] 2021-11-25 16:30
Should we wait until this one is merged & released? https://github.com/gnosis/safe-react/pull/3062

**Closed** 2021-12-13 14:11 UTC
Labels: Enhancement ✨
