### ISSUE TITLE
Using Eth in the Multisend Transaction Builder app

### ISSUE THREAD

**Issue by travisformayor** [gnosis/safe-react-apps#129] opened 2021-05-12 05:29 UTC
Multisend transaction builder doesn't let you make batch multisend trasactions using just Eth, instead requiring an abi to begin. Asked about this in the Discord and was told its possible in the contact, but the UI would need to be updated to support it. Thanks.

<img width="419" alt="Screen Shot 2021-05-11 at 10 28 24 PM" src="https://user-images.githubusercontent.com/14283780/117923012-35b16480-b2a8-11eb-8ea5-60e9eba16bb4.png">

<img width="827" alt="Screen Shot 2021-05-11 at 10 25 04 PM" src="https://user-images.githubusercontent.com/14283780/117922713-bd4aa380-b2a7-11eb-8ad1-e78dcdf144a7.png">

**Comment by tschubotz** [comment] 2021-06-04 09:06
This should be fixed with #108 I think. We just haven't released it yet.

**Comment by liliya-soroka** [comment] 2021-09-16 12:04
The issue is closed, as #108 was released.
The issue may be reopened if it's still actual even after #108

**Closed by liliya-soroka** 2021-09-16 12:04 UTC
