### ISSUE TITLE
[Discord] WalletConnect Safe App is not loading

### ISSUE THREAD

**Issue by sche** [gnosis/safe-react-apps#99] opened 2021-02-20 08:08 UTC
https://discordapp.com/channels/477106835862716416/477391201708802058/812439570003132426

Is the wallet connect safe app broken right now?  All I get is a blank white frame when trying to load it
The first time I tried to load it up I got a loading symbol.  Left it for 15 minutes and nothin'.  Did a hard refresh of the page and reconnected to my Safe.  Now I don't even get the loading symbol.

Just to see, I was able to load up some of the other safe apps like the Aave and Compound ones

**Comment by tschubotz** [comment] 2021-02-22 08:43
(Just transferred it to safe-react-apps)

I'm not able to reproduce this issue.

We serve the WalletConnect app from https://cloudflare-ipfs.com/ipfs/QmT3VxxfFtfEcvq8AeaoFAyUGxePRa2zisvnxLTrQXU5Uf - Does this load for the user?

As Richard mentioned, we need more context. Things like
- Web or desktop?
- Which browser?
- Which owner wallet?
- Which env.

Basically things that are in the bug issue template ;)

**Comment by mikheevm** [comment] 2021-02-22 08:47
@tschubotz afaik we serve it from ipfs.io not cloudlfare. Was it changed?

**Comment by tschubotz** [comment] 2021-02-22 08:56
@mikheevm this was a bit of a hidden change in the 3.0.1 release due to the many rate limit errors with ipfs.io :) 
https://gnosisinc.slack.com/archives/C63LQTGNB/p1613573599230800

**Comment by mikheevm** [comment] 2021-02-25 10:09
The user figured it out, the problem was on their side:
```
[8:26 AM] bitznbrewz: FIGURED IT OUT
[8:29 AM] bitznbrewz: K, soooo, I had connected with my Trezor wallet through metamask.  I just connected using Trezor Bridge in Firefox and now it seems ok.  :thumbsup:.  I was actually unable to get the bridge to work in Brave browser.

But, going forward, I guess I will make sure to use the native Trezor integration with Gnosis
```

**Closed by mikheevm** 2021-02-25 10:09 UTC
