### ISSUE TITLE
[WalletConnect] Wrong client info used

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-react-apps#56] opened 2020-10-05 15:55 UTC
Currently the WalletConnect safe app uses the meta information from the root [index.html](https://github.com/gnosis/safe-react-apps/blob/development/public/index.html). This is because the wallet connect sdk tries to parse them. 

See https://github.com/gnosis/safe-react-apps/pull/54#issuecomment-703681329

# Expected

Name: Gnosis Safe Multisig
Logo: 
![image](https://user-images.githubusercontent.com/1380529/99513767-42a16b00-298b-11eb-9e48-dfa0e09ddb4f.png) (That's just a screenshot, I think the logo should be in the project already. If not, please let me know.)

# Updates

- Nov 18, Tobi: Added expected behavior

**Comment by anxolin** [comment] 2020-10-08 11:55
Yep, interested in this one since we use the returned image is broken:

![image](https://user-images.githubusercontent.com/2352112/95455269-e3a10d00-096d-11eb-8211-0d7f2495d4ae.png)

This is the information that's being sent:
![image](https://user-images.githubusercontent.com/2352112/95455326-fadffa80-096d-11eb-942d-437b529f9be4.png)

**Comment by tschubotz** [comment] 2020-11-02 15:46
Requires to refactor the way we do Safe apps. (gnosis/safe-react-apps#55)

**Comment by tschubotz** [comment] 2020-11-13 16:10
This will most likely be resolved once the gnosis/safe-react-apps#55 issue is released -> to check

**Comment by nicosampler** [comment] 2020-11-17 16:53
this should be fixed @tschubotz @rmeissner could you re-check? And close if everything is ok.

**Comment by tschubotz** [comment] 2020-11-18 09:43
@nicosampler this is how it looks now: 
![image](https://user-images.githubusercontent.com/1380529/99513118-9495c100-298a-11eb-9eea-746d063c9445.png)

Seems to work, except we display the WalletConnect logo. I think we should return the Gnosis Safe logo though.
Also as name I would use just "Gnosis Safe Multisig" instead of "Gnosis Safe Multisig WalletConect".

We should have made this more clear in the issue description what the expected behavior is, sorry.
I'll add this now.

**Comment by dasanra** [comment] 2020-11-19 08:48
@tschubotz what do you think about this?

![Captura de pantalla de 2020-11-19 09-46-51.png](https://images.zenhubusercontent.com/5f030e579c03aa152acf03e2/a5fa55e2-d075-4af4-a16e-80b1a5067141)

**Comment by tschubotz** [comment] 2020-11-19 08:58
> @tschubotz what do you think about this?

Looks perfect to me!

**Comment by dasanra** [comment] 2020-11-19 09:22
Link for testing:

https://ipfs.io/ipfs/QmfZUg9egmkFfNiGMLMcZPE7Ft7CBfsZ98Poq4qUj6qgJH/

**Closed** 2020-11-19 14:57 UTC
Labels: Bug 🐛
